#!/bin/bash
# GitHub Actions Setup Checklist for Remix Chess Arena
# Run through these steps to enable automated Docker builds

echo "=== GitHub Actions & Docker Hub Setup ==="
echo ""
echo "✓ Already completed locally:"
echo "  - Dockerfile with multi-stage build"
echo "  - docker-compose.yml with healthcheck"
echo "  - .github/workflows/docker-build.yml created"
echo "  - Image pushed to Docker Hub: domin8/remix-chess-arena:latest"
echo ""
echo "Next steps to enable CI/CD:"
echo ""
echo "1. Create GitHub Repository"
echo "   - Go to https://github.com/new"
echo "   - Create a repository named 'remix-chess-arena'"
echo "   - DO NOT initialize with README (you have files)"
echo ""
echo "2. Add GitHub Secrets"
echo "   - Go to https://github.com/<YOUR_USERNAME>/remix-chess-arena"
echo "   - Click Settings → Secrets and variables → Actions"
echo "   - Create two secrets:"
echo ""
echo "     a) DOCKER_HUB_USERNAME"
echo "        Value: domin8"
echo ""
echo "     b) DOCKER_HUB_TOKEN"
echo "        Value: (your Docker Hub Personal Access Token)"
echo ""
echo "3. Get Docker Hub Personal Access Token"
echo "   - Visit: https://hub.docker.com/settings/security"
echo "   - Click 'New Access Token'"
echo "   - Name: github-actions-remix-chess"
echo "   - Permissions: Read & Write"
echo "   - Copy token and paste into GitHub Secret"
echo ""
echo "4. Push Code to GitHub"
echo "   cd /path/to/remix-chess-arena"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Add Docker & CI/CD setup'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/<YOUR_USERNAME>/remix-chess-arena.git"
echo "   git push -u origin main"
echo ""
echo "5. Verify CI/CD Works"
echo "   - Go to GitHub Actions tab"
echo "   - Watch the 'Build and Push to Docker Hub' workflow"
echo "   - Verify it completes successfully (~3 minutes)"
echo "   - Check Docker Hub for new image tags"
echo ""
echo "=== Verification Commands ==="
echo ""
echo "# Test locally"
echo "docker compose up -d"
echo "docker compose ps  # Should show (healthy)"
echo "curl http://localhost:3000"
echo ""
echo "# Test from Docker Hub"
echo "docker pull domin8/remix-chess-arena:latest"
echo "docker run -d -p 3001:3000 domin8/remix-chess-arena:latest"
echo "curl http://localhost:3001"
echo ""
echo "=== Troubleshooting ==="
echo ""
echo "Issue: Secrets not working"
echo "Fix: Verify exactly as shown above (DOCKER_HUB_USERNAME=domin8, not github username)"
echo ""
echo "Issue: Build fails with 'unauthorized'"
echo "Fix: Check token has Read & Write permissions on Docker Hub"
echo ""
echo "Issue: Image not on Docker Hub after push"
echo "Fix: Check GitHub Actions workflow logs for errors"
echo ""
echo "=== Completed Setup ==="
echo ""
echo "✓ Dockerfile        - Multi-stage, 130MB compressed, healthcheck ready"
echo "✓ docker-compose.yml - Production-ready with healthcheck"
echo "✓ GitHub Actions     - Automated build on push to main/develop"
echo "✓ Docker Hub Push    - Initial image already pushed"
echo "✓ Healthcheck       - Enabled (nc -z 127.0.0.1 3000)"
echo ""
